# Generated by Django 4.0.6 on 2022-11-07 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcases', models.TextField()),
                ('solvedcases', models.TextField()),
                ('onprogress', models.TextField()),
                ('others', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Case Study ',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='newsimg')),
                ('posted_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News ',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=100)),
                ('crimetype', models.TextField(blank=True)),
                ('description', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='crimeimg')),
                ('case_status', models.CharField(max_length=100)),
                ('case_start_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Criminal Records ',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimetype', models.CharField(choices=[('Robbery', 'Robbery'), ('Domestic Volience', 'Domestic Volience'), ('Sexual Harassment', 'Sexual Harassment'), ('Missing person', 'Missing person')], max_length=25)),
                ('victimname', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=25, null=True)),
                ('reportingperson', models.CharField(max_length=50)),
                ('incidentdate', models.DateField()),
                ('incidentlocation', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('no_of_people', models.TextField(blank=True)),
                ('affected', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile Table',
            },
        ),
    ]
